# !! CHANGE BASE URL !!
baseURL = 'https://cpm2025.pangenome.eu/'
languageCode = 'en-us'
title = 'CPM 2025'
theme = "mainroad"
mainSections = ["p"]

[Params.logo]
image = "img/cpm-logo-small.png" # Logo image. Path relative to "static"

[Params.sidebar]
home = "left" # Configure layout for home page
list = "right"  # Configure layout for list pages
widgets = ["sidebar_menu"]
single = false

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      hardWraps = false
      unsafe = true
